import { FindingActionTemplate } from "@/features/findings/types";
import { QuizDefinition, QuizQuestion } from "@/features/quizzes/types";

type QuizActionTemplateMap = Record<string, Record<string, FindingActionTemplate>>;

const SEEDED_ACTION_TEMPLATES: QuizActionTemplateMap = {
  "air-fragrance": {
    q1: {
      title: "Remove plug-ins and automatic air fresheners",
      whyItMatters: "Continuous fragrance devices can keep indoor exposure patterns elevated.",
      minimumStep: "Unplug fragrance devices and pause room fragrance gels for 14 days.",
      lowCostUpgrade: "Use ventilation and simple odor-control basics in high-use areas.",
      premiumUpgrade: "Pair the reset with a bedroom HEPA purifier for a cleaner baseline.",
      feasibility: 1.24,
      triggerOnHighAnswer: true,
    },
    q2: {
      title: "Reduce combustion-based fragrance sources",
      whyItMatters: "Frequent burning can add recurring indoor air load.",
      minimumStep: "Limit candles/incense to occasional use and ventilate while in use.",
      lowCostUpgrade: "Shift ambiance to non-combustion options for most days.",
      premiumUpgrade: "If burning is kept, run purifier support in the same room.",
      feasibility: 1.02,
      triggerOnHighAnswer: true,
    },
    q3: {
      title: "Stop dryer sheets and scent boosters",
      whyItMatters: "Laundry fragrance can create repeated contact through clothes and bedding.",
      minimumStep: "Pause dryer sheets and scent boosters for the next two weeks.",
      lowCostUpgrade: "Use wool dryer balls and fragrance-free detergent defaults.",
      premiumUpgrade: "Add a full bedding and towel laundry reset routine.",
      feasibility: 1.18,
      triggerOnHighAnswer: true,
    },
    q4: {
      title: "Remove fabric softener from default laundry",
      whyItMatters: "Fabric softener can reinforce repetitive fragrance contact.",
      minimumStep: "Stop fabric softener and monitor comfort for 14 days.",
      lowCostUpgrade: "Use a simplified non-fragrance softening approach instead.",
      premiumUpgrade: "Pair with a complete laundry system reset.",
      feasibility: 1.16,
      triggerOnHighAnswer: true,
    },
    q5: {
      title: "Simplify personal care fragrance load",
      whyItMatters: "Daily personal care can become a high-frequency fragrance pathway.",
      minimumStep: "Pause perfume/cologne and replace one daily-use product this week.",
      lowCostUpgrade: "Swap your top two high-use items to fragrance-free options.",
      premiumUpgrade: "Run a 30-day full lineup reset for hair/body/lotion products.",
      feasibility: 1.08,
      triggerOnHighAnswer: true,
    },
    q6: {
      title: "Use unscented cleaning as the default",
      whyItMatters: "Frequent scented spray use can keep exposure patterns active indoors.",
      minimumStep: "Pause scented routine sprays and use unscented alternatives.",
      lowCostUpgrade: "Create a simple two-product unscented cleaning system.",
      premiumUpgrade: "Add deeper tools (like steam cleaning) where it fits your routine.",
      feasibility: 1.14,
      triggerOnHighAnswer: true,
    },
    q7: {
      title: "Remove room spray and odor masking habits",
      whyItMatters: "Odor masking products can add repeated fragrance exposure.",
      minimumStep: "Stop room sprays for 14 days and test ventilation-first alternatives.",
      lowCostUpgrade: "Use targeted odor source cleanup instead of masking products.",
      premiumUpgrade: "Add purifier support in frequently used rooms.",
      feasibility: 1.22,
      triggerOnHighAnswer: true,
    },
    q8: {
      title: "Establish a daily ventilation habit",
      whyItMatters: "Consistent fresh-air exchange helps stabilize indoor air quality baseline.",
      minimumStep: "Open windows for 5-10 minutes daily when conditions allow.",
      lowCostUpgrade: "Use kitchen and bathroom fan routines with the ventilation habit.",
      premiumUpgrade: "Add simple indoor humidity/air checks for better timing.",
      feasibility: 1.26,
      triggerOnHighAnswer: false,
    },
    q9: {
      title: "Track symptom-linked fragrance patterns",
      whyItMatters: "Observed sensitivity patterns can help prioritize practical exposure swaps.",
      minimumStep: "Log when symptoms and fragrance exposure appear together for 2 weeks.",
      lowCostUpgrade: "Use your log to remove top triggering products first.",
      premiumUpgrade: "Create a stricter home fragrance protocol for shared spaces.",
      feasibility: 0.96,
      triggerOnHighAnswer: true,
    },
    q10: {
      title: "Set a higher-protection air baseline for sensitive households",
      whyItMatters: "Higher-sensitivity contexts often benefit from tighter air and fragrance defaults.",
      minimumStep: "Prioritize fragrance-free defaults in core rooms this week.",
      lowCostUpgrade: "Run purifier support during sleep and high-occupancy periods.",
      premiumUpgrade: "Adopt a full-room protocol for laundry, cleaning, and air flow.",
      feasibility: 0.94,
      triggerOnHighAnswer: false,
    },
  },
  water: {
    q1: {
      title: "Upgrade your drinking water baseline",
      whyItMatters: "Drinking water is a daily pathway, so filter consistency matters.",
      minimumStep: "Pick one primary filtered source and use it as your daily default.",
      lowCostUpgrade: "Keep filtered water prepared to avoid tap fallback during busy days.",
      premiumUpgrade: "Move to a stronger filtration tier when you can maintain it consistently.",
      feasibility: 1.15,
      triggerOnHighAnswer: true,
    },
    q2: {
      title: "Run a local water baseline check",
      whyItMatters: "Knowing local water context helps target practical filter decisions.",
      minimumStep: "Review your utility report and capture a short baseline summary.",
      lowCostUpgrade: "Match your filtration setup to the top concerns from the report.",
      premiumUpgrade: "Set an annual review reminder for local water data.",
      feasibility: 1.2,
      triggerOnHighAnswer: false,
    },
    q3: {
      title: "Reduce routine plastic bottle intake",
      whyItMatters: "Frequent plastic bottle use can become a recurring exposure habit.",
      minimumStep: "Replace daily plastic bottle use with one reusable bottle baseline.",
      lowCostUpgrade: "Create a refill routine before leaving home.",
      premiumUpgrade: "Build a full out-of-home hydration setup for travel and work.",
      feasibility: 1.22,
      triggerOnHighAnswer: true,
    },
    q4: {
      title: "Eliminate heated-plastic drinking patterns",
      whyItMatters: "Heat plus plastic is a high-priority pattern to remove first.",
      minimumStep: "Set a rule to never drink from plastic bottles left in heat.",
      lowCostUpgrade: "Use stainless or glass as your default carry bottle.",
      premiumUpgrade: "Create spare-bottle routines for car, gym, and travel use.",
      feasibility: 1.25,
      triggerOnHighAnswer: true,
    },
    q5: {
      title: "Filter all hot drinks and cooking water",
      whyItMatters: "Cooking and hot beverages contribute meaningful daily water intake.",
      minimumStep: "Use filtered water for hot drinks and cooking for the next 30 days.",
      lowCostUpgrade: "Set up a dedicated kitchen filtered-water station.",
      premiumUpgrade: "Standardize this rule in your weekly kitchen prep routine.",
      feasibility: 1.12,
      triggerOnHighAnswer: false,
    },
    q6: {
      title: "Add a shower filter baseline",
      whyItMatters: "Shower exposure is frequent and can affect skin/hair comfort patterns.",
      minimumStep: "Install a shower filter this week.",
      lowCostUpgrade: "Set cartridge replacement reminders immediately after setup.",
      premiumUpgrade: "Integrate shower filter maintenance into your home calendar.",
      feasibility: 1.04,
      triggerOnHighAnswer: true,
    },
    q7: {
      title: "Address shower-related skin and hair irritation patterns",
      whyItMatters: "Persistent discomfort can signal a water-baseline adjustment opportunity.",
      minimumStep: "Track symptom changes after shower filter and gentle routine updates.",
      lowCostUpgrade: "Use brief cooler-rinse and fragrance-light products while testing.",
      premiumUpgrade: "Run a 30-day water + personal-care reset protocol.",
      feasibility: 0.98,
      triggerOnHighAnswer: true,
    },
    q8: {
      title: "Reduce over-reliance on fridge-filter water",
      whyItMatters: "Fridge filters vary and can be under-maintained in day-to-day use.",
      minimumStep: "Treat fridge water as secondary unless replacement timing is confirmed.",
      lowCostUpgrade: "Use your primary filter source for most drinking water.",
      premiumUpgrade: "Create a maintenance schedule for every active filter point.",
      feasibility: 1.08,
      triggerOnHighAnswer: false,
    },
    q9: {
      title: "Create an out-of-home water strategy",
      whyItMatters: "Consistency often breaks outside home unless defaults are prepared.",
      minimumStep: "Carry a reusable bottle when leaving home this week.",
      lowCostUpgrade: "Set a simple refill rule before errands, work, or travel.",
      premiumUpgrade: "Build a ready travel hydration kit for regular routines.",
      feasibility: 1.2,
      triggerOnHighAnswer: false,
    },
    q10: {
      title: "Use a higher-protection water protocol for sensitive contexts",
      whyItMatters: "Sensitivity-focused households usually benefit from tighter water defaults.",
      minimumStep: "Adopt filtered drinking and no-heated-plastic rules immediately.",
      lowCostUpgrade: "Add filtered cooking and shower filter consistency.",
      premiumUpgrade: "Lock in a stable long-term water maintenance protocol.",
      feasibility: 0.92,
      triggerOnHighAnswer: true,
    },
  },
  "cleaning-sprays": {
    q1: {
      title: "Replace disinfecting wipes with reusable cleaning tools",
      whyItMatters: "High-frequency wipes can increase repeated residue contact in core areas.",
      minimumStep: "Pause routine disinfecting wipes for two weeks in kitchen and bathroom zones.",
      lowCostUpgrade: "Use microfiber cloths plus a simple unscented cleaner for daily cleanup.",
      premiumUpgrade: "Set up a reusable wipe and wash cycle to make the swap permanent.",
      feasibility: 1.22,
      triggerOnHighAnswer: true,
    },
    q2: {
      title: "Remove aerosol disinfectant sprays from default routine",
      whyItMatters: "Aerosol cleaners can concentrate indoor exposure during routine cleaning.",
      minimumStep: "Stop aerosol disinfectants for routine tasks this week.",
      lowCostUpgrade: "Apply cleaner to cloth first instead of spraying into the room.",
      premiumUpgrade: "Use a low-fume deep-clean method for weekly resets.",
      feasibility: 1.2,
      triggerOnHighAnswer: true,
    },
    q3: {
      title: "Shift to unscented all-purpose cleaning defaults",
      whyItMatters: "Scented routine sprays can keep exposure patterns active without added cleaning value.",
      minimumStep: "Swap one high-use scented spray to an unscented option.",
      lowCostUpgrade: "Standardize one unscented all-purpose formula across most surfaces.",
      premiumUpgrade: "Build a simplified two-product cleaning kit by zone.",
      feasibility: 1.14,
      triggerOnHighAnswer: false,
    },
    q4: {
      title: "Reduce heavy-fume cleaner use",
      whyItMatters: "Bleach/ammonia-style products can create high-intensity exposure moments.",
      minimumStep: "Pause heavy-fume cleaners for routine jobs and reserve only for defined cases.",
      lowCostUpgrade: "Use gentler alternatives for standard bathroom and kitchen cleaning.",
      premiumUpgrade: "Create a written decision guide for when stronger chemistry is truly required.",
      feasibility: 1.1,
      triggerOnHighAnswer: true,
    },
    q5: {
      title: "Add a cleaning ventilation protocol",
      whyItMatters: "Ventilation reduces accumulated indoor load while cleaning.",
      minimumStep: "Open windows or run fan support before and during cleaning sessions.",
      lowCostUpgrade: "Use a fixed 10-minute post-clean airflow routine.",
      premiumUpgrade: "Pair cleaning schedule with consistent room-air reset timing.",
      feasibility: 1.25,
      triggerOnHighAnswer: true,
    },
    q6: {
      title: "Improve enclosed-space cleaning approach",
      whyItMatters: "Small enclosed zones can trap fumes when routines are not adjusted.",
      minimumStep: "Break enclosed-area cleaning into short intervals with airflow breaks.",
      lowCostUpgrade: "Use lower-fume products first in shower/toilet/under-sink zones.",
      premiumUpgrade: "Create a zone-by-zone checklist for enclosed spaces.",
      feasibility: 1.06,
      triggerOnHighAnswer: false,
    },
    q7: {
      title: "Reserve antibacterial products for specific scenarios",
      whyItMatters: "Default antibacterial usage can add unnecessary repeated exposure.",
      minimumStep: "Use standard soap/cleaning for routine days and reserve antibacterial products selectively.",
      lowCostUpgrade: "Create a short list of true high-risk situations where disinfecting is needed.",
      premiumUpgrade: "Separate normal-clean and illness-clean supplies to avoid overuse.",
      feasibility: 1.12,
      triggerOnHighAnswer: false,
    },
    q8: {
      title: "Simplify floor-cleaning chemistry",
      whyItMatters: "Frequent strong floor products can add repeat contact in high-traffic areas.",
      minimumStep: "Swap to one lower-fume floor cleaner this week.",
      lowCostUpgrade: "Use reusable mop pads and dilute product consistently.",
      premiumUpgrade: "Add steam-assisted deep clean on a reduced chemical schedule.",
      feasibility: 1.13,
      triggerOnHighAnswer: false,
    },
    q9: {
      title: "Use symptom patterns to prioritize cleaning swaps",
      whyItMatters: "Observed discomfort around cleaning can identify the highest-impact adjustments.",
      minimumStep: "Track symptoms with date, product, and room for 2 weeks.",
      lowCostUpgrade: "Remove top symptom-linked products first.",
      premiumUpgrade: "Adopt a stable low-fume cleaning protocol across all main zones.",
      feasibility: 0.98,
      triggerOnHighAnswer: true,
    },
    q10: {
      title: "Set a sensitivity-aware cleaning baseline",
      whyItMatters: "Higher-sensitivity households benefit from tighter cleaning defaults.",
      minimumStep: "Use unscented, low-fume cleaning products for core daily routines.",
      lowCostUpgrade: "Increase ventilation and avoid aerosol products in shared spaces.",
      premiumUpgrade: "Create a fixed household-safe cleaning kit and routine cadence.",
      feasibility: 0.95,
      triggerOnHighAnswer: true,
    },
  },
  "cookware-food-storage": {
    q1: {
      title: "Set a safer daily cookware baseline",
      whyItMatters: "Your most-used cookware determines repeated food-contact patterns.",
      minimumStep: "Choose one safer daily pan style and use it for most cooking this week.",
      lowCostUpgrade: "Rotate high-heat cooking toward stainless, cast iron, or enamel options.",
      premiumUpgrade: "Complete a core cookware reset for high-use items.",
      feasibility: 1.12,
      triggerOnHighAnswer: false,
    },
    q2: {
      title: "Retire scratched or flaking nonstick first",
      whyItMatters: "Worn nonstick is a high-priority replacement pattern.",
      minimumStep: "Remove visibly worn nonstick cookware from active rotation.",
      lowCostUpgrade: "Replace highest-use worn piece first with a safer alternative.",
      premiumUpgrade: "Run a full audit and staged replacement plan for all worn pieces.",
      feasibility: 1.2,
      triggerOnHighAnswer: true,
    },
    q3: {
      title: "Reduce high-heat nonstick use",
      whyItMatters: "High heat with nonstick increases avoidable kitchen exposure load.",
      minimumStep: "Avoid high-heat settings on nonstick this week.",
      lowCostUpgrade: "Use medium heat and preheat alternatives for stick-prone foods.",
      premiumUpgrade: "Shift high-heat tasks to non-nonstick cookware by default.",
      feasibility: 1.16,
      triggerOnHighAnswer: true,
    },
    q4: {
      title: "Replace hot-pan plastic utensil contact",
      whyItMatters: "Frequent plastic contact on heat can be reduced with simple tool swaps.",
      minimumStep: "Retire one high-use plastic utensil used on hot cookware.",
      lowCostUpgrade: "Set a core tool set of wood, stainless, or heat-safe silicone.",
      premiumUpgrade: "Complete a drawer reset to remove recurring heat-contact plastics.",
      feasibility: 1.19,
      triggerOnHighAnswer: false,
    },
    q5: {
      title: "Shift leftover storage toward glass defaults",
      whyItMatters: "Storage habits become a daily exposure pathway when repeated over time.",
      minimumStep: "Use glass for leftovers you plan to reheat this week.",
      lowCostUpgrade: "Keep matching glass containers ready in high-use sizes.",
      premiumUpgrade: "Adopt a hot-food-to-glass default household rule.",
      feasibility: 1.15,
      triggerOnHighAnswer: false,
    },
    q6: {
      title: "Stop reheating in plastic",
      whyItMatters: "Heat-plus-plastic patterns are a high-impact adjustment target.",
      minimumStep: "Move all reheating to glass or ceramic containers.",
      lowCostUpgrade: "Use plate or lid alternatives instead of plastic wrap during reheat.",
      premiumUpgrade: "Convert your top five meal-prep containers to glass.",
      feasibility: 1.24,
      triggerOnHighAnswer: true,
    },
    q7: {
      title: "Upgrade hot-drink container defaults",
      whyItMatters: "Daily drink containers can become a repeat hot-contact pathway.",
      minimumStep: "Use stainless or glass for one daily drink habit.",
      lowCostUpgrade: "Set a no-heated-plastic bottle rule for car and gym contexts.",
      premiumUpgrade: "Create a fixed home-and-travel drink container kit.",
      feasibility: 1.2,
      triggerOnHighAnswer: false,
    },
    q8: {
      title: "Reduce hot takeout container contact time",
      whyItMatters: "Frequent hot-food-in-plastic patterns are a clear upgrade opportunity.",
      minimumStep: "Transfer hot takeout to plate or glass soon after pickup.",
      lowCostUpgrade: "Set takeout reheating and leftover transfer rules in your kitchen flow.",
      premiumUpgrade: "Add a repeatable takeout protocol for home and work routines.",
      feasibility: 1.18,
      triggerOnHighAnswer: true,
    },
    q9: {
      title: "Lower packaged-food reliance in key staples",
      whyItMatters: "Reducing high-frequency packaged defaults improves overall food-contact profile.",
      minimumStep: "Swap one frequently used packaged staple this week.",
      lowCostUpgrade: "Create a short low-packaging staple list for repeat shopping.",
      premiumUpgrade: "Build a weekly baseline menu with lower packaging reliance.",
      feasibility: 1.03,
      triggerOnHighAnswer: false,
    },
    q10: {
      title: "Use a sensitivity-focused kitchen baseline",
      whyItMatters: "Sensitive contexts often benefit from faster standardization of kitchen defaults.",
      minimumStep: "Prioritize no-heated-plastic and no-worn-nonstick rules this month.",
      lowCostUpgrade: "Expand glass and stainless defaults for highest-use workflows.",
      premiumUpgrade: "Lock in a consistent cookware/storage protocol across all meal types.",
      feasibility: 0.93,
      triggerOnHighAnswer: true,
    },
  },
  "food-reset": {
    q1: {
      title: "Reduce restaurant and takeout frequency",
      whyItMatters: "Frequent outside meals can compound additive and oil exposure patterns.",
      minimumStep: "Reduce current outside-meal frequency by one step this week.",
      lowCostUpgrade: "Use a simple order rule: protein, carb, produce with fewer fried items.",
      premiumUpgrade: "Set a repeatable home-meal baseline that replaces most takeout days.",
      feasibility: 1.14,
      triggerOnHighAnswer: true,
    },
    q2: {
      title: "Lower deep-fried food frequency",
      whyItMatters: "Repeated fried choices can keep food-reset progress slower.",
      minimumStep: "Pause deep-fried items for 14 days.",
      lowCostUpgrade: "Default to grilled, roasted, or baked options when eating out.",
      premiumUpgrade: "Set a standing no-fried default for weekday meals.",
      feasibility: 1.08,
      triggerOnHighAnswer: false,
    },
    q3: {
      title: "Replace one ultra-processed daily default",
      whyItMatters: "Ultra-processed routines are high-frequency inputs that add up quickly.",
      minimumStep: "Swap one processed snack or meal with a simple whole-food alternative.",
      lowCostUpgrade: "Build a short clean-convenience shelf for busy days.",
      premiumUpgrade: "Run a 30-day reduced-processed baseline with planned staples.",
      feasibility: 1.13,
      triggerOnHighAnswer: true,
    },
    q4: {
      title: "Simplify sauces and condiment defaults",
      whyItMatters: "Condiments can quietly increase daily additive and sugar load.",
      minimumStep: "Remove one high-use sauce from daily rotation this week.",
      lowCostUpgrade: "Keep 2-3 lower-additive condiments as your fixed baseline.",
      premiumUpgrade: "Use homemade or minimal-ingredient sauces for most meals.",
      feasibility: 1.1,
      triggerOnHighAnswer: true,
    },
    q5: {
      title: "Reduce daily sugar and sweet-drink patterns",
      whyItMatters: "Frequent sugary inputs can destabilize energy and appetite rhythm.",
      minimumStep: "Remove sugary drinks for the next 14 days.",
      lowCostUpgrade: "Plan 1-2 intentional sweet windows weekly instead of daily intake.",
      premiumUpgrade: "Use a stable breakfast/lunch template to reduce repeat cravings.",
      feasibility: 1.19,
      triggerOnHighAnswer: true,
    },
    q6: {
      title: "Trim artificial sweetener reliance",
      whyItMatters: "Frequent sweetener products can maintain a high-sweetness baseline.",
      minimumStep: "Pause one daily sweetener product this week.",
      lowCostUpgrade: "Swap diet drinks to water-forward alternatives.",
      premiumUpgrade: "Audit protein bars and powders for high-sweetener defaults.",
      feasibility: 1.08,
      triggerOnHighAnswer: true,
    },
    q7: {
      title: "Reduce routine food-dye intake",
      whyItMatters: "Color-additive reduction is a practical cleanup for packaged snacks/drinks.",
      minimumStep: "Remove one dyed product category from home stock this week.",
      lowCostUpgrade: "Use a no-dye label check on regular purchases.",
      premiumUpgrade: "Run a pantry scan to remove recurring dye-heavy products.",
      feasibility: 1.04,
      triggerOnHighAnswer: false,
    },
    q8: {
      title: "Audit health-halo processed foods",
      whyItMatters: "Some fitness-branded products still create high processed-food reliance.",
      minimumStep: "Replace one high-use bar or snack with a simpler option.",
      lowCostUpgrade: "Set two consistent real-food snack defaults.",
      premiumUpgrade: "Keep packaged convenience products as backup only.",
      feasibility: 1.05,
      triggerOnHighAnswer: false,
    },
    q9: {
      title: "Increase home-cooked meal frequency",
      whyItMatters: "Home cooking improves control and consistency across the full week.",
      minimumStep: "Cook one simple meal per day for the next five days.",
      lowCostUpgrade: "Rotate the same three low-friction meals to reduce decision load.",
      premiumUpgrade: "Add a short weekly prep and shopping routine.",
      feasibility: 1.12,
      triggerOnHighAnswer: true,
    },
    q10: {
      title: "Apply a sensitivity-focused food baseline",
      whyItMatters: "Sensitivity-focused goals respond best to stable, repeatable food defaults.",
      minimumStep: "Run a 30-day baseline with fewer fried foods and fewer additives.",
      lowCostUpgrade: "Use a mostly-home meal pattern with consistent staples.",
      premiumUpgrade: "Lock in a structured meal system that minimizes variability.",
      feasibility: 0.94,
      triggerOnHighAnswer: true,
    },
  },
  laundry: {
    q1: {
      title: "Switch daily detergent to fragrance-light baseline",
      whyItMatters: "Detergent sets repeated fabric-contact exposure across all loads.",
      minimumStep: "Use a fragrance-free or lower-fragrance detergent for new loads this week.",
      lowCostUpgrade: "Reserve scented products for rare loads only.",
      premiumUpgrade: "Standardize one detergent system across clothing and bedding.",
      feasibility: 1.14,
      triggerOnHighAnswer: true,
    },
    q2: {
      title: "Remove dryer sheets and scent boosters",
      whyItMatters: "Scent boosters can create high-frequency residue on clothes and bedding.",
      minimumStep: "Pause scent boosters and dryer sheets for 14 days.",
      lowCostUpgrade: "Use wool dryer balls as default dry-cycle support.",
      premiumUpgrade: "Add periodic extra-rinse cycles for high-contact fabrics.",
      feasibility: 1.23,
      triggerOnHighAnswer: true,
    },
    q3: {
      title: "Stop routine fabric softener use",
      whyItMatters: "Fabric softener can increase ongoing residue layers in high-use textiles.",
      minimumStep: "Remove fabric softener from regular laundry cycles.",
      lowCostUpgrade: "Use a simpler softening approach only when needed.",
      premiumUpgrade: "Run a full fabric reset for towels and sheets.",
      feasibility: 1.18,
      triggerOnHighAnswer: true,
    },
    q4: {
      title: "Limit disinfecting laundry additives",
      whyItMatters: "Routine additive use is often higher than needed for daily laundry hygiene.",
      minimumStep: "Pause antibacterial/disinfecting additives for standard loads.",
      lowCostUpgrade: "Use additive-free defaults except clearly defined situations.",
      premiumUpgrade: "Create a simple hygiene protocol with fewer additive products.",
      feasibility: 1.09,
      triggerOnHighAnswer: true,
    },
    q5: {
      title: "Improve bedding-wash consistency",
      whyItMatters: "Bedding cadence affects daily comfort and residue turnover.",
      minimumStep: "Set a recurring weekly or biweekly bedding schedule.",
      lowCostUpgrade: "Add midweek pillowcase changes for high-contact use.",
      premiumUpgrade: "Use a rotating bedding calendar for all household members.",
      feasibility: 1.17,
      triggerOnHighAnswer: false,
    },
    q6: {
      title: "Address musty washer or fabric patterns",
      whyItMatters: "Musty signals suggest moisture/buildup routines need adjustment.",
      minimumStep: "Run a washer clean cycle and dry seals/drum after loads.",
      lowCostUpgrade: "Leave washer door and drawer open until fully dry.",
      premiumUpgrade: "Set a monthly washer maintenance schedule.",
      feasibility: 1.21,
      triggerOnHighAnswer: true,
    },
    q7: {
      title: "Improve post-load washer airflow habit",
      whyItMatters: "Consistent airflow after loads reduces repeat moisture buildup.",
      minimumStep: "Leave washer open after every cycle this week.",
      lowCostUpgrade: "Add a small reminder near laundry zone until habit is automatic.",
      premiumUpgrade: "Pair airflow habit with monthly gasket and filter checks.",
      feasibility: 1.24,
      triggerOnHighAnswer: false,
    },
    q8: {
      title: "Simplify stain and whitening chemistry",
      whyItMatters: "Frequent strong booster use can increase routine chemical load.",
      minimumStep: "Use targeted stain treatment only on true stains this week.",
      lowCostUpgrade: "Switch to one gentler stain method for regular loads.",
      premiumUpgrade: "Create a fabric-type stain protocol with fewer products.",
      feasibility: 1.06,
      triggerOnHighAnswer: false,
    },
    q9: {
      title: "Reduce high-synthetic laundry intensity",
      whyItMatters: "Synthetic-heavy loads benefit from adjusted wash strategy and textile planning.",
      minimumStep: "Use full loads and gentler settings for synthetic-heavy items.",
      lowCostUpgrade: "Add microfiber-capture support for synthetic cycles.",
      premiumUpgrade: "Shift high-contact purchases toward natural-fiber defaults over time.",
      feasibility: 1.01,
      triggerOnHighAnswer: false,
    },
    q10: {
      title: "Apply sensitivity-first laundry defaults",
      whyItMatters: "High-sensitivity contexts respond to stable fragrance-light laundry routines.",
      minimumStep: "Use consistent low-fragrance products for all skin-contact loads.",
      lowCostUpgrade: "Add extra-rinse cycles for towels, sheets, and underlayers.",
      premiumUpgrade: "Create a separate safe-load protocol for sensitive household members.",
      feasibility: 0.93,
      triggerOnHighAnswer: true,
    },
  },
  "mind-stress": {
    q1: {
      title: "Set a daily stress downshift anchor",
      whyItMatters: "A predictable downshift practice helps reduce ongoing mental overload.",
      minimumStep: "Use a 5-minute breathing reset at the same time each day.",
      lowCostUpgrade: "Stack breathing with a short walk or stretch block.",
      premiumUpgrade: "Create a fixed morning regulation routine.",
      feasibility: 1.25,
      triggerOnHighAnswer: true,
    },
    q2: {
      title: "Reduce wired/restless carryover",
      whyItMatters: "Frequent restless states can disrupt focus and recovery rhythm.",
      minimumStep: "Add one scheduled no-input pause each afternoon.",
      lowCostUpgrade: "Use a short body-based reset before high-stress blocks.",
      premiumUpgrade: "Adopt structured daytime regulation intervals.",
      feasibility: 1.16,
      triggerOnHighAnswer: true,
    },
    q3: {
      title: "Limit high-stress content intake",
      whyItMatters: "Repeated threat-style media can sustain mental activation patterns.",
      minimumStep: "Limit one high-trigger app to scheduled windows.",
      lowCostUpgrade: "Use app timers and remove push notifications for stress-heavy feeds.",
      premiumUpgrade: "Create a full digital-boundary schedule for workdays and evenings.",
      feasibility: 1.2,
      triggerOnHighAnswer: true,
    },
    q4: {
      title: "Protect wake/sleep phone boundaries",
      whyItMatters: "Phone bookends influence overall stress tone across the day.",
      minimumStep: "No phone for first 20 minutes after waking and last 30 before bed.",
      lowCostUpgrade: "Charge phone outside immediate bed reach.",
      premiumUpgrade: "Set a full no-phone-in-bed protocol with replacement routine.",
      feasibility: 1.18,
      triggerOnHighAnswer: false,
    },
    q5: {
      title: "Replace stress-coping substance defaults",
      whyItMatters: "Frequent state-shift substances can reduce baseline self-regulation capacity.",
      minimumStep: "Use one non-substance coping action before default coping habit.",
      lowCostUpgrade: "Build a 3-step coping ladder (breathe, move, connect).",
      premiumUpgrade: "Run a 14-day structured reset on your top coping behavior.",
      feasibility: 1.05,
      triggerOnHighAnswer: true,
    },
    q6: {
      title: "Interrupt rumination and avoidance loops",
      whyItMatters: "Spiral and avoidance patterns can increase stress persistence.",
      minimumStep: "Use a 3-minute note: what is true, what is next, when it happens.",
      lowCostUpgrade: "Use a fixed daily journaling prompt for loop interruption.",
      premiumUpgrade: "Adopt a time-boxed decision system for recurring stressors.",
      feasibility: 1.12,
      triggerOnHighAnswer: true,
    },
    q7: {
      title: "Increase recovery-practice frequency",
      whyItMatters: "Recovery habits support consistent nervous-system reset capacity.",
      minimumStep: "Schedule two intentional calming practices this week.",
      lowCostUpgrade: "Move to 10 minutes daily with one repeatable practice.",
      premiumUpgrade: "Build a full evening wind-down sequence.",
      feasibility: 1.23,
      triggerOnHighAnswer: true,
    },
    q8: {
      title: "Use movement as a daily stress outlet",
      whyItMatters: "Regular movement is a practical stress-regulation support.",
      minimumStep: "Add a 10-20 minute walk today.",
      lowCostUpgrade: "Set a 3-4 day weekly movement baseline.",
      premiumUpgrade: "Adopt a structured movement plan with recovery blocks.",
      feasibility: 1.2,
      triggerOnHighAnswer: false,
    },
    q9: {
      title: "Increase consistent social connection",
      whyItMatters: "Reliable connection can buffer stress and reduce isolation drift.",
      minimumStep: "Schedule one meaningful check-in this week.",
      lowCostUpgrade: "Set a daily touchpoint habit (call/text/in-person).",
      premiumUpgrade: "Create a recurring weekly connection ritual.",
      feasibility: 1.09,
      triggerOnHighAnswer: false,
    },
    q10: {
      title: "Use a sensitivity-focused stress baseline",
      whyItMatters: "High stress sensitivity benefits from fixed, repeatable recovery defaults.",
      minimumStep: "Run a 14-day baseline: breathing, reduced doomscrolling, and daily movement.",
      lowCostUpgrade: "Add phone bookend limits and structured wind-down routine.",
      premiumUpgrade: "Adopt a locked-in nervous-system protocol until stability improves.",
      feasibility: 0.9,
      triggerOnHighAnswer: true,
    },
  },
  "personal-care": {
    q1: {
      title: "Reduce fragrance/parfum in leave-on products",
      whyItMatters: "Daily leave-on fragrance creates repeated high-frequency contact patterns.",
      minimumStep: "Replace one high-use leave-on fragrance product this week.",
      lowCostUpgrade: "Prioritize fragrance-light swaps for lotion, deodorant, and hair leave-ins.",
      premiumUpgrade: "Build a full fragrance-light personal care baseline.",
      feasibility: 1.14,
      triggerOnHighAnswer: true,
    },
    q2: {
      title: "Limit routine perfume/cologne use",
      whyItMatters: "Frequent concentrated scent usage can add daily inhalation load.",
      minimumStep: "Pause perfume/cologne for 14 days.",
      lowCostUpgrade: "Reserve fragrance use for occasional events only.",
      premiumUpgrade: "Set a no-daily-fragrance personal standard.",
      feasibility: 1.18,
      triggerOnHighAnswer: true,
    },
    q3: {
      title: "Simplify deodorant and antiperspirant routine",
      whyItMatters: "Underarm products are high-frequency, high-contact daily inputs.",
      minimumStep: "Switch to a simpler deodorant option for routine use.",
      lowCostUpgrade: "Reduce strong fragrance and frequent reapplication patterns.",
      premiumUpgrade: "Build a stable sweat-management routine across product and clothing choices.",
      feasibility: 1.11,
      triggerOnHighAnswer: true,
    },
    q4: {
      title: "Reduce leave-on skincare layering",
      whyItMatters: "High product layering can increase exposure and routine complexity.",
      minimumStep: "Use a short baseline routine for 14 days (cleanser + moisturizer + SPF as needed).",
      lowCostUpgrade: "Remove one non-essential layer per week.",
      premiumUpgrade: "Use a staged add-back process for only high-value products.",
      feasibility: 1.12,
      triggerOnHighAnswer: true,
    },
    q5: {
      title: "Trim daily leave-in hair product load",
      whyItMatters: "Multiple leave-in products can create repeated all-day exposure.",
      minimumStep: "Replace your top leave-in with a simpler option.",
      lowCostUpgrade: "Keep one leave-in default instead of layered products.",
      premiumUpgrade: "Run a complete hair-routine simplification reset.",
      feasibility: 1.09,
      triggerOnHighAnswer: true,
    },
    q6: {
      title: "Adjust full-body leave-on use patterns",
      whyItMatters: "Large-area leave-on products are a meaningful routine input.",
      minimumStep: "Use fragrance-light body care on targeted areas first.",
      lowCostUpgrade: "Apply only where needed instead of automatic full-body layering.",
      premiumUpgrade: "Build a consistent skin-barrier routine with fewer products.",
      feasibility: 1.03,
      triggerOnHighAnswer: false,
    },
    q7: {
      title: "Simplify long-wear makeup routine",
      whyItMatters: "Repeated long-wear layering can be reduced while preserving routine goals.",
      minimumStep: "Swap one high-use long-wear product this week.",
      lowCostUpgrade: "Use lighter makeup days when long wear is not needed.",
      premiumUpgrade: "Create a compact clean kit for frequent-use items.",
      feasibility: 1.04,
      triggerOnHighAnswer: false,
    },
    q8: {
      title: "Upgrade sunscreen baseline options",
      whyItMatters: "Sunscreen is a high-coverage product where consistency and formulation matter.",
      minimumStep: "Test one mineral-forward daily sunscreen option.",
      lowCostUpgrade: "Keep one face and one body option you will actually use consistently.",
      premiumUpgrade: "Pair sunscreen routine with practical sun-smart behavior defaults.",
      feasibility: 1.05,
      triggerOnHighAnswer: true,
    },
    q9: {
      title: "Reduce high-frequency nail chemistry exposure",
      whyItMatters: "Frequent gel/acrylic/remover cycles can be lowered with spacing changes.",
      minimumStep: "Take a 2-4 week break from gel/acrylic cycles.",
      lowCostUpgrade: "Increase spacing between treatments.",
      premiumUpgrade: "Set a low-frequency long-term nail maintenance schedule.",
      feasibility: 0.98,
      triggerOnHighAnswer: false,
    },
    q10: {
      title: "Set a sensitivity-first personal care protocol",
      whyItMatters: "High sensitivity often improves with consistent, low-variability products.",
      minimumStep: "Run a 30-day simple fragrance-light routine across top daily products.",
      lowCostUpgrade: "Pause perfume/cologne and reduce multi-step layering during reset.",
      premiumUpgrade: "Create a locked-in safe kit with no random product rotation.",
      feasibility: 0.92,
      triggerOnHighAnswer: true,
    },
  },
  "pest-control": {
    q1: {
      title: "Stop routine indoor bug spray use",
      whyItMatters: "Frequent indoor spray use can create repeated indoor residue patterns.",
      minimumStep: "Pause indoor sprays for routine pest response this month.",
      lowCostUpgrade: "Use prevention and targeted alternatives before spray choices.",
      premiumUpgrade: "Build a fixed home pest-response protocol.",
      feasibility: 1.2,
      triggerOnHighAnswer: true,
    },
    q2: {
      title: "Remove foggers and bug bombs from defaults",
      whyItMatters: "Whole-room treatments can produce broad residue without solving root drivers.",
      minimumStep: "Remove fogger/bug-bomb products from active supplies.",
      lowCostUpgrade: "Use targeted interventions only for specific pest patterns.",
      premiumUpgrade: "Run post-treatment cleanup and prevention checklist if previously used.",
      feasibility: 1.1,
      triggerOnHighAnswer: true,
    },
    q3: {
      title: "Review professional spray frequency",
      whyItMatters: "Frequent scheduled spraying may be reducible with stronger prevention controls.",
      minimumStep: "Review current service cadence and identify one prevention-first adjustment.",
      lowCostUpgrade: "Request targeted treatment zones instead of blanket routine spraying.",
      premiumUpgrade: "Shift to prevention-led service plan with periodic audits.",
      feasibility: 1.03,
      triggerOnHighAnswer: true,
    },
    q4: {
      title: "Switch default response from spray-first to prevention-first",
      whyItMatters: "Response strategy determines both exposure load and recurrence outcomes.",
      minimumStep: "Use one prevention action before any spray decision.",
      lowCostUpgrade: "Keep traps/barriers ready so spray is not the first move.",
      premiumUpgrade: "Document pest-specific response steps for household consistency.",
      feasibility: 1.16,
      triggerOnHighAnswer: true,
    },
    q5: {
      title: "Reduce recurring indoor pest frequency",
      whyItMatters: "Frequent sightings signal unresolved entry, food, or moisture drivers.",
      minimumStep: "Track pest location and timing for 7 days to identify main driver.",
      lowCostUpgrade: "Address top driver first (food, moisture, or entry points).",
      premiumUpgrade: "Run a full-home prevention audit by zone.",
      feasibility: 1.07,
      triggerOnHighAnswer: true,
    },
    q6: {
      title: "Tighten food storage and cleanup rhythm",
      whyItMatters: "Open food and crumbs can sustain pest recurrence patterns.",
      minimumStep: "Run a nightly 5-minute kitchen reset this week.",
      lowCostUpgrade: "Use sealed storage for top pest-attracting staples.",
      premiumUpgrade: "Complete pantry and under-sink food-zone reset.",
      feasibility: 1.2,
      triggerOnHighAnswer: false,
    },
    q7: {
      title: "Improve trash and drain consistency",
      whyItMatters: "Drain/trash patterns strongly influence fruit fly and roach recurrence.",
      minimumStep: "Set fixed trash and drain-clean cadence this week.",
      lowCostUpgrade: "Add checklist reminders for evening sink/drain reset.",
      premiumUpgrade: "Create a weekly sanitation and moisture-control schedule.",
      feasibility: 1.18,
      triggerOnHighAnswer: false,
    },
    q8: {
      title: "Seal priority entry points",
      whyItMatters: "Entry-point control reduces reliance on recurring chemical interventions.",
      minimumStep: "Seal one high-probability entry gap this week.",
      lowCostUpgrade: "Add door sweep and screen checks to monthly home routine.",
      premiumUpgrade: "Complete perimeter and under-sink crack audit with staged fixes.",
      feasibility: 1.1,
      triggerOnHighAnswer: false,
    },
    q9: {
      title: "Use targeted alternatives before chemistry escalation",
      whyItMatters: "Simple alternatives can reduce repeated broad spray exposure.",
      minimumStep: "Use one targeted alternative method for your current pest type.",
      lowCostUpgrade: "Keep category-specific kits (ant/fruit fly/spider) ready to use.",
      premiumUpgrade: "Build seasonal pest protocols with prevention-first timing.",
      feasibility: 1.14,
      triggerOnHighAnswer: false,
    },
    q10: {
      title: "Apply sensitivity-focused pest-control defaults",
      whyItMatters: "Higher-sensitivity households benefit from stable prevention-first methods.",
      minimumStep: "Use no-spray-first baseline for 30 days.",
      lowCostUpgrade: "Standardize safe kit and sealing routine across core rooms.",
      premiumUpgrade: "Adopt scheduled prevention maintenance to reduce reactive treatments.",
      feasibility: 0.93,
      triggerOnHighAnswer: true,
    },
  },
  "sleep-environment": {
    q1: {
      title: "Stabilize sleep/wake timing",
      whyItMatters: "Schedule consistency is foundational for stable sleep quality.",
      minimumStep: "Set a fixed wake time for the next 7 days.",
      lowCostUpgrade: "Keep bedtime within a 60-90 minute band nightly.",
      premiumUpgrade: "Adopt consistent weekday/weekend sleep timing plan.",
      feasibility: 1.22,
      triggerOnHighAnswer: true,
    },
    q2: {
      title: "Reduce last-hour screen exposure",
      whyItMatters: "Late screen habits can delay downshift and sleep readiness.",
      minimumStep: "Set a 30-minute no-screen window before bed tonight.",
      lowCostUpgrade: "Extend to a 60-minute nightly screen curfew.",
      premiumUpgrade: "Set a full night-mode routine with device cutover rules.",
      feasibility: 1.19,
      triggerOnHighAnswer: true,
    },
    q3: {
      title: "Improve bedroom darkness",
      whyItMatters: "Night light leakage can reduce sleep depth and continuity.",
      minimumStep: "Remove or cover visible bedroom light sources tonight.",
      lowCostUpgrade: "Add blackout support for primary light leaks.",
      premiumUpgrade: "Complete a full dark-room audit and maintenance setup.",
      feasibility: 1.16,
      triggerOnHighAnswer: true,
    },
    q4: {
      title: "Remove media-on while falling asleep",
      whyItMatters: "Sleep-on-media patterns can increase sleep fragmentation.",
      minimumStep: "No videos or TV audio during sleep onset tonight.",
      lowCostUpgrade: "Use a low-stimulation wind-down replacement activity.",
      premiumUpgrade: "Adopt a no-phone-in-bed and no-TV-in-bedroom protocol.",
      feasibility: 1.17,
      triggerOnHighAnswer: true,
    },
    q5: {
      title: "Optimize sleeping temperature range",
      whyItMatters: "Temperature comfort strongly affects sleep continuity.",
      minimumStep: "Lower room temperature slightly tonight and adjust bedding layers.",
      lowCostUpgrade: "Add fan-based airflow support at bedtime.",
      premiumUpgrade: "Set a consistent overnight room-temperature program.",
      feasibility: 1.15,
      triggerOnHighAnswer: false,
    },
    q6: {
      title: "Set a caffeine cutoff boundary",
      whyItMatters: "Late caffeine timing can disrupt sleep depth and wake-after-sleep onset.",
      minimumStep: "Set no-caffeine-after-noon for 14 days.",
      lowCostUpgrade: "Move cutoff earlier if wakeups remain frequent.",
      premiumUpgrade: "Replace afternoon caffeine ritual with non-stimulant routine.",
      feasibility: 1.21,
      triggerOnHighAnswer: true,
    },
    q7: {
      title: "Improve alcohol timing relative to bedtime",
      whyItMatters: "Late alcohol can increase nighttime disruption even when sleep onset feels easy.",
      minimumStep: "Avoid alcohol within 3 hours of bedtime this week.",
      lowCostUpgrade: "Reduce weekly frequency by one step.",
      premiumUpgrade: "Run a sleep-first month to compare baseline differences.",
      feasibility: 1.08,
      triggerOnHighAnswer: false,
    },
    q8: {
      title: "Set a night wake-up recovery protocol",
      whyItMatters: "Consistent 2 AM response habits can reduce prolonged wake episodes.",
      minimumStep: "If awake more than 15 minutes, avoid phone and use calm reset routine.",
      lowCostUpgrade: "Use low-light and no clock-checking policy during wake episodes.",
      premiumUpgrade: "Adopt a scripted back-to-sleep sequence for consistency.",
      feasibility: 1.06,
      triggerOnHighAnswer: true,
    },
    q9: {
      title: "Improve bedroom air baseline",
      whyItMatters: "Stuffy or dry sleep-air environments can contribute to poor sleep continuity.",
      minimumStep: "Ventilate bedroom daily and declutter around sleep zone.",
      lowCostUpgrade: "Add airflow and humidity checks to evening routine.",
      premiumUpgrade: "Set a fixed sleep-air setup with maintenance reminders.",
      feasibility: 1.05,
      triggerOnHighAnswer: true,
    },
    q10: {
      title: "Use a sensitivity-focused sleep baseline",
      whyItMatters: "High sleep sensitivity benefits from tight, repeatable sleep defaults.",
      minimumStep: "Run a 14-day baseline: fixed wake time, dark room, and screen/caffeine boundaries.",
      lowCostUpgrade: "Add cool-room and alcohol-timing rules during baseline period.",
      premiumUpgrade: "Lock in a full nightly protocol until sleep stability improves.",
      feasibility: 0.91,
      triggerOnHighAnswer: true,
    },
  },
};

function sanitizePrompt(prompt: string): string {
  const compact = prompt.replace(/\s+/g, " ").trim().replace(/[?.!]+$/, "");
  return compact.length > 84 ? `${compact.slice(0, 81)}...` : compact;
}

function buildFallbackTemplate(quiz: QuizDefinition, question: QuizQuestion): FindingActionTemplate {
  const compactPrompt = sanitizePrompt(question.prompt);

  return {
    title: `Adjust: ${compactPrompt}`,
    whyItMatters: `This answer indicates a repeatable exposure pattern in ${quiz.category}.`,
    minimumStep: "Choose one lower-exposure adjustment for this pattern this week.",
    lowCostUpgrade: "Turn that adjustment into a default routine for the next 30 days.",
    premiumUpgrade: "Upgrade tools or products only after the baseline habit is stable.",
    feasibility: 1.05,
    triggerOnHighAnswer: false,
  };
}

export function getActionTemplate(quiz: QuizDefinition, question: QuizQuestion): FindingActionTemplate {
  const byQuiz = SEEDED_ACTION_TEMPLATES[quiz.id];

  if (byQuiz && byQuiz[question.id]) {
    return byQuiz[question.id];
  }

  return buildFallbackTemplate(quiz, question);
}
